// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSWVLGq9xtXFYciGtzIz_gRtKDAVo-SmI',
    appId: '1:934476804809:web:189f6cd7f8da6c95049318',
    messagingSenderId: '934476804809',
    projectId: 'mlbank-41602',
    authDomain: 'mlbank-41602.firebaseapp.com',
    storageBucket: 'mlbank-41602.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3b0L94Pv_rwKCExjFXSzaQDdMn_EtPA',
    appId: '1:934476804809:android:97b93deaa1a0a151049318',
    messagingSenderId: '934476804809',
    projectId: 'mlbank-41602',
    storageBucket: 'mlbank-41602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsW_y9-lT4DtSSVX9MOjenxxBTVR4Fifo',
    appId: '1:934476804809:ios:4446cad049cf2218049318',
    messagingSenderId: '934476804809',
    projectId: 'mlbank-41602',
    storageBucket: 'mlbank-41602.appspot.com',
    iosClientId: '934476804809-ae6dmblap1f7111bqoa00ras2ao62nv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsW_y9-lT4DtSSVX9MOjenxxBTVR4Fifo',
    appId: '1:934476804809:ios:4446cad049cf2218049318',
    messagingSenderId: '934476804809',
    projectId: 'mlbank-41602',
    storageBucket: 'mlbank-41602.appspot.com',
    iosClientId: '934476804809-ae6dmblap1f7111bqoa00ras2ao62nv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlbank',
  );
}
